spring.application.name=transacao

management.endpoints.web.exposure.include=health,metrics,swagger-ui,info,prometheus
management.endpoint.health.show-details = always

management.metrics.enable.all=true
springdoc.show-actuator=true
management.endpoint.prometheus.enabled=true